name: Full tarball

on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: checkout modules
        run: git submodule update --init --recursive
      - name: create zip
        run: |
          git archive -o REAL_SOURCE_CODE.zip HEAD
          git submodule --quiet foreach 'cd $toplevel; zip -ru REAL_SOURCE_CODE.zip $sm_path'
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: REAL_SOURCE_CODE.zip
