name: Full tarball

on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: checkout modules
        run: git submodule update --init --recursive
      - name: test cd
        run: |
          cd ..
          ls
      - name: create tar.gz
        run: |
          git archive -o SOURCE.CODE.+.submodules.tar HEAD
          git submodule --quiet foreach 'cd $toplevel; tar -uf SOURCE.CODE.+.submodules.tar $sm_path'
          gzip -9 SOURCE.CODE.+.submodules.tar
      - name: create zip
        run: |
          git archive -o SOURCE\ CODE\ +\ submodules.zip HEAD
          git submodule --quiet foreach 'cd $toplevel; zip -ru SOURCE\ CODE\ +\ submodules.zip $sm_path'
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SOURCE\ CODE\ +\ submodules.tar.gz
            SOURCE\ CODE\ +\ submodules.zip
